# Setup
name: Aliou Diallo
description: Aliou Diallo is a developer living in Paris.
twitter: '@aliouftw'

# Blog permalinks
permalink: /posts/:year/:month/:title

# Pagination settings
paginate: 5
paginate_path: '/:num'

# Deps.
gems:
  - jekyll-assets
  - jekyll-paginate

exclude: [Gemfile, Gemfile.lock]

# Assets configuration.
assets:
  compress:
    css: true
  digest: true
  compass:
    css: sass

# Google stuff.
google:
  verification: 'QnLybeTUEt_VtHQVLLtEz0WflVe-H7TNqCOTlF-tfz8'
  analytics: 'UA-47951031-4'
