name: Aliou Diallo
description: Aliou Diallo is a developer living in Paris.
twitter: '@aliouftw'

google:
  verification: 'QnLybeTUEt_VtHQVLLtEz0WflVe-H7TNqCOTlF-tfz8'
  analytics: 'UA-47951031-4'

plugins:
  - jekyll-assets

exclude: [Gemfile, Gemfile.lock]

assets:
  compression: true
