name: Aliou Diallo
description: Aliou Diallo is a backend developer from Paris.
twitter: '@aliouftw'

gems:
  - jekyll-assets

exclude: [Gemfile, Gemfile.lock, vendor]

assets:
  compess:
    css: sass
