name: Aliou Diallo
description: Aliou Diallo is a developer living in Paris.
twitter: '@aliouftw'

author:
  name: Aliou Diallo
  url: https://aliou.me

google:
  verification: 'QnLybeTUEt_VtHQVLLtEz0WflVe-H7TNqCOTlF-tfz8'

plugins:
  - jekyll-assets

exclude: [Gemfile, Gemfile.lock, .circleci, vendor, .ruby-version]

assets:
  compression: true
  gzip: true

# Permalinks
permalink: /posts/:year/:month/:title/
