name: Aliou Diallo
description: Aliou Diallo is a developer living in Paris.
twitter: '@aliouftw'

google:
  verification: 'QnLybeTUEt_VtHQVLLtEz0WflVe-H7TNqCOTlF-tfz8'

plugins:
  - jekyll-assets

exclude: [Gemfile, Gemfile.lock, .circleci, vendor]

assets:
  compression: true

# Permalinks
permalink: /posts/:year/:month/:title/
