defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-rubygems-{{ checksum "Gemfile.lock" }}
            - v1-rubygems-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Jekyll build
          command: bundle exec jekyll build

      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-html \
              --disable-external

      - save_cache:
          key: v1-rubygems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
